name: cloudchat
description: Chat with your friends.
publish_to: none
# On version bump also increase the build number for F-Droid
version: 1.1.3+30

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  adaptive_dialog: ^2.1.0
  animations: ^2.0.11
  archive: ^3.4.10
  async: ^2.11.0
  audioplayers: ^6.1.0
  audioplayers_windows: ^4.0.0
  badges: ^3.1.2
  blurhash_dart: ^1.2.1
  chewie: ^1.11.0
  collection: ^1.18.0
  cross_file: ^0.3.4+2
  cupertino_icons: any
  desktop_drop: ^0.4.4
  desktop_notifications: ^0.6.3
  device_info_plus: ^10.0.1
  dynamic_color: ^1.7.0
  emoji_picker_flutter: ^3.1.0
  emojis: ^0.9.9
  sqlcipher_library_windows: ^1.0.2
  fcm_shared_isolate: ^0.2.0
  file_picker: ^8.1.2
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_foreground_task: ^6.1.3
  flutter_highlighter: ^0.1.1
  flutter_html: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^17.2.3
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_math_fork:
    git: https://github.com/Telosnex/flutter_math_fork_fork.git
  flutter_olm: 2.0.0
  flutter_ringtone_player: ^4.0.0+2
  flutter_new_badger: ^1.1.1
  flutter_openssl_crypto: ^0.5.0
  flutter_secure_storage: ^9.2.2
  flutter_shortcuts_new: ^2.0.0
  flutter_typeahead: ## Custom fork from flutter_typeahead since the package is not maintain well.
    git:
      url: https://github.com/famedly/flutter_typeahead.git
      ref: main
  flutter_web_auth_2: ^4.1.0 # Version 4 blocked by https://github.com/MixinNetwork/flutter-plugins/issues/379
  flutter_webrtc: 0.14.0
  go_router: ^14.8.1
  handy_window: ^0.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.4
  http: ^1.2.0
  image: ^4.1.7
  image_picker: ^1.1.0
  intl: any
  just_audio: ^0.9.39
  just_audio_windows: ^0.2.2
  latlong2: ^0.9.1
  linkify: ^5.0.0
  local_notifier: ^0.1.6
  matrix: ^0.39.1
  mime: ^1.0.6
  native_imaging: ^0.2.0
  opus_caf_converter_dart: ^1.0.1
  package_info_plus: ^8.0.2
  pasteboard: ^0.2.0
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  pretty_qr_code: ^3.2.1
  provider: ^6.0.2
  punycode: ^1.0.0
  qr_code_scanner_plus: ^2.0.10+1
  qr_image: ^1.0.0
  receive_sharing_intent: ^1.8.1
  record: ^5.1.2
  rxdart: ^0.28.0
  scroll_to_index: ^3.0.1
  share_plus: ^10.0.2
  shared_preferences: ^2.2.0 # Pinned because https://github.com/flutter/flutter/issues/118401
  slugify: ^2.0.0
  sqflite_common_ffi: ^2.3.3
  sqlcipher_flutter_libs: ^0.6.1
  swipe_to_action: ^0.3.0
  tor_detector_web: ^1.1.0
  app_links: ^6.3.3
  unifiedpush: ^5.0.1
  unifiedpush_ui: ^0.1.0
  universal_html: ^2.2.4
  url_launcher: ^6.2.5
  vibration: ^3.1.3
  video_compress: ^3.1.4
  video_player: ^2.9.2
  wakelock_plus: ^1.2.2
  webrtc_interface: 1.2.2+hotfix.2
  window_manager: ^0.4.3
  windows_single_instance: ^1.0.1
  windows_taskbar: ^1.1.2
  launch_at_startup: ^0.3.1
  tray_manager: ^0.3.2
  idle_detector_wrapper: ^1.0.0
  markdown_editor_plus: ^0.2.15
  flutter_single_instance: 
    path: lib/packages/flutter_single_instance
  glass: ^2.0.0+2
  noise_meter: ^5.0.2
  open_file: ^3.5.10


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.0.3+1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  integration_test:
    sdk: flutter
  license_checker: ^1.6.0
  msix: ^3.6.2
  translations_cleaner: ^0.0.5

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/info-logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
    - assets/sounds/call.ogg
    - assets/js/
    - assets/js/package/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: fonts/Roboto/RobotoMono-Regular.ttf
    - family: SegoeUIEmoji
      fonts:
        - asset: fonts/SegoeUIEmoji/seguiemj.ttf

msix_config:
  display_name: CloudChat
  publisher_display_name: CloudChat
  publisher: CN=CloudChat, O=Head of bad integration tests, L=Matrix, S=Internet, C=EU
  identity_name: chat.cloud.cloudchat
  logo_path: assets\logo.png
  capabilities: internetClient, location, microphone, webcam
  protocol_activation: https
  app_uri_handler_hosts: cloudchat.im, matrix.to
  execution_alias: cloudchat
  sign_msix: false
  install_certificate: false

dependency_overrides:
  win32: 5.5.3
